### ISSUE TITLE
Does not start on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by JoeNyland** [sbooth/Tag#3]
After installing macOS 10.15 Catalina, Tag no longer starts:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/7666402/66586187-20ca9780-eb80-11e9-90b4-8815fa8d909b.png">

Any chance that we can get a 64-bit version released that will allow us to run this on macOS 10.15 and later? Please 🙏

**Comment by JoeNyland** [comment]
If it can't be updated, is there a recommended alternative to Tag for newer Macs?

**Comment by sbooth** [comment]
I created a branch to track Catalina compatibility

**Comment by JoeNyland** [comment]
Hey @sbooth, does that mean you're hoping to add support for Catalina?

**Comment by JoeNyland** [comment]
I have no idea what I'm doing, but I wanted to try and help: I've just had a go at trying to get this to build using Xcode 11 but I'm just getting error after error and can't get it to build 😕

**Comment by jsumners** [comment]
☹️  just tried opening and building. Seems all of the xibs just won't work. Not being much of macOS developer, I'm not sure how to fix them.

**Comment by JoeNyland** [comment]
Closing this as I no longer have the desire to run this and have migrated to using https://picard.musicbrainz.org/.
